### ISSUE TITLE
Upgrades to scheduler module

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#104]
## Must have features

- [x] GPU selection for training jobs
  - [x] Select next available *n* GPUs (#92)
  - [x] Select specific *n* GPUs (#19)
  - [x] Testing

## Nice to have features

- [ ] Restart jobs (this would help: https://github.com/BVLC/caffe/pull/2253)
  - [ ] Pause jobs
  - [ ] Restart jobs after pausing or aborting (#24)
    - [ ] Choose a different GPU when restarting
- [ ] Auto-scaling of dataset jobs to make most of available resources

**Comment by cancan101** [comment]
Would this task also include cluster based scheduling (e.g. #108)?

**Comment by lukeyeager** [comment]
> Would this task also include cluster based scheduling (e.g. #108)?

Not yet, but I'm thinking about it as I'm refactoring the scheduler.

**Comment by lukeyeager** [comment]
Closing this since all "must have" features are complete.
